/**
 * Sync product version + GitHub repo from voicesub-types to Cargo / npm / Tauri / TS.
 *
 * Source of truth: crates/voicesub-types/src/version.rs
 *   - PROJECT_VERSION
 *   - DEFAULT_GITHUB_REPO  → src/lib/brand.ts GITHUB_REPO
 * Usage:
 *   node scripts/sync-version.mjs        # write derived files
 *   node scripts/sync-version.mjs --check  # exit 1 on drift
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const checkOnly = process.argv.includes("--check");

const VERSION_RS = path.join(root, "crates", "voicesub-types", "src", "version.rs");
const CARGO_TOML = path.join(root, "Cargo.toml");
const PACKAGE_JSON = path.join(root, "package.json");
const PACKAGE_LOCK = path.join(root, "package-lock.json");
const TAURI_CONF = path.join(root, "src-tauri", "tauri.conf.json");
const PROJECT_VERSION_TS = path.join(root, "src", "lib", "project-version.ts");
const BRAND_TS = path.join(root, "src", "lib", "brand.ts");
const SITE_MAIN_JS = path.join(root, "site", "main.js");

const VERSION_RE =
  /^pub const PROJECT_VERSION:\s*&str\s*=\s*"([^"]+)";\s*$/m;
const GITHUB_REPO_RE =
  /^pub const DEFAULT_GITHUB_REPO:\s*&str\s*=\s*"([^"]+)";\s*$/m;
const BRAND_GITHUB_REPO_RE =
  /^(export const GITHUB_REPO\s*=\s*")([^"]+)(";\s*)$/m;
const SITE_GITHUB_REPO_RE =
  /^( {2}const GITHUB_REPO = ")([^"]+)(";\s*)$/m;
const WORKSPACE_VERSION_RE =
  /(\[workspace\.package\][\s\S]*?^version\s*=\s*")([^"]+)(")/m;

function readText(filePath) {
  return fs.readFileSync(filePath, "utf8");
}

function writeText(filePath, content) {
  fs.writeFileSync(filePath, content, "utf8");
}

function normalizeNewlines(text) {
  return text.replace(/\r\n/g, "\n");
}

function readVersionRsConstants() {
  const source = readText(VERSION_RS);
  const versionMatch = source.match(VERSION_RE);
  if (!versionMatch) {
    throw new Error(
      `Could not parse PROJECT_VERSION from ${path.relative(root, VERSION_RS)}`,
    );
  }
  const version = versionMatch[1].trim();
  if (!/^\d+\.\d+\.\d+([.-].+)?$/.test(version)) {
    throw new Error(`Invalid PROJECT_VERSION: ${version}`);
  }
  const repoMatch = source.match(GITHUB_REPO_RE);
  if (!repoMatch) {
    throw new Error(
      `Could not parse DEFAULT_GITHUB_REPO from ${path.relative(root, VERSION_RS)}`,
    );
  }
  const githubRepo = repoMatch[1].trim();
  if (!/^[^/\s]+\/[^/\s]+$/.test(githubRepo)) {
    throw new Error(`Invalid DEFAULT_GITHUB_REPO: ${githubRepo}`);
  }
  return { version, githubRepo };
}

function patchBrandGithubRepo(content, githubRepo) {
  if (!BRAND_GITHUB_REPO_RE.test(content)) {
    throw new Error(
      `Could not find export const GITHUB_REPO in ${path.relative(root, BRAND_TS)}`,
    );
  }
  return content.replace(BRAND_GITHUB_REPO_RE, `$1${githubRepo}$3`);
}

function patchSiteGithubRepo(content, githubRepo) {
  if (!SITE_GITHUB_REPO_RE.test(content)) {
    throw new Error(
      `Could not find const GITHUB_REPO in ${path.relative(root, SITE_MAIN_JS)}`,
    );
  }
  return content.replace(SITE_GITHUB_REPO_RE, `$1${githubRepo}$3`);
}

function expectedProjectVersionTs(version) {
  return [
    "/** Generated by scripts/sync-version.mjs — do not edit by hand. */",
    `export const PROJECT_VERSION = "${version}";`,
    "",
  ].join("\n");
}

function workspaceCargoVersion(content) {
  const match = content.match(WORKSPACE_VERSION_RE);
  return match ? match[2] : null;
}

function patchCargoToml(content, version) {
  if (!WORKSPACE_VERSION_RE.test(content)) {
    throw new Error(
      `Could not find [workspace.package].version in ${path.relative(root, CARGO_TOML)}`,
    );
  }
  return content.replace(WORKSPACE_VERSION_RE, `$1${version}$3`);
}

/** Replace top-level JSON "version" without reformatting the rest of the file. */
function patchTopLevelJsonVersion(content, version) {
  const next = content.replace(
    /^(\s*"version"\s*:\s*")([^"]+)(")/m,
    `$1${version}$3`,
  );
  if (next === content) {
    const parsed = JSON.parse(content);
    if (parsed.version !== version) {
      throw new Error('Could not patch top-level "version" field in JSON');
    }
  }
  return next;
}

function patchPackageLock(content, version) {
  let next = content;
  next = next.replace(
    /^(\s*"name"\s*:\s*"kagevi-subtitles"\s*,\s*\n\s*"version"\s*:\s*")([^"]+)(")/m,
    `$1${version}$3`,
  );
  next = next.replace(
    /^(\s*""\s*:\s*\{\s*\n\s*"name"\s*:\s*"kagevi-subtitles"\s*,\s*\n\s*"version"\s*:\s*")([^"]+)(")/m,
    `$1${version}$3`,
  );
  const data = JSON.parse(next);
  const rootOk = data.version === version;
  const pkgOk = data.packages?.[""]?.version === version;
  if (!rootOk || !pkgOk) {
    data.version = version;
    if (data.packages?.[""]) {
      data.packages[""].version = version;
    }
    return `${JSON.stringify(data, null, 2)}\n`;
  }
  return next;
}

function main() {
  const { version, githubRepo } = readVersionRsConstants();
  const relative = (filePath) => path.relative(root, filePath);
  const drifted = [];

  const cargoContent = readText(CARGO_TOML);
  const packageData = JSON.parse(readText(PACKAGE_JSON));
  const lockData = JSON.parse(readText(PACKAGE_LOCK));
  const tauriData = JSON.parse(readText(TAURI_CONF));
  const brandContent = readText(BRAND_TS);
  const brandRepoMatch = brandContent.match(BRAND_GITHUB_REPO_RE);
  const brandRepo = brandRepoMatch ? brandRepoMatch[2] : null;
  const tsExpected = expectedProjectVersionTs(version);
  const tsCurrent = fs.existsSync(PROJECT_VERSION_TS)
    ? readText(PROJECT_VERSION_TS)
    : "";

  if (workspaceCargoVersion(cargoContent) !== version) {
    drifted.push(relative(CARGO_TOML));
    if (!checkOnly) {
      writeText(CARGO_TOML, patchCargoToml(cargoContent, version));
    }
  }

  if (packageData.version !== version) {
    drifted.push(relative(PACKAGE_JSON));
    if (!checkOnly) {
      writeText(
        PACKAGE_JSON,
        patchTopLevelJsonVersion(readText(PACKAGE_JSON), version),
      );
    }
  }

  const lockRoot = lockData.version;
  const lockPkg = lockData.packages?.[""]?.version;
  if (lockRoot !== version || lockPkg !== version) {
    drifted.push(relative(PACKAGE_LOCK));
    if (!checkOnly) {
      writeText(PACKAGE_LOCK, patchPackageLock(readText(PACKAGE_LOCK), version));
    }
  }

  if (tauriData.version !== version) {
    drifted.push(relative(TAURI_CONF));
    if (!checkOnly) {
      writeText(
        TAURI_CONF,
        patchTopLevelJsonVersion(readText(TAURI_CONF), version),
      );
    }
  }

  if (normalizeNewlines(tsCurrent) !== normalizeNewlines(tsExpected)) {
    drifted.push(relative(PROJECT_VERSION_TS));
    if (!checkOnly) {
      writeText(PROJECT_VERSION_TS, tsExpected);
    }
  }

  if (brandRepo !== githubRepo) {
    drifted.push(relative(BRAND_TS));
    if (!checkOnly) {
      writeText(BRAND_TS, patchBrandGithubRepo(brandContent, githubRepo));
    }
  }

  const siteContent = readText(SITE_MAIN_JS);
  const siteRepoMatch = siteContent.match(SITE_GITHUB_REPO_RE);
  const siteRepo = siteRepoMatch ? siteRepoMatch[2] : null;
  if (siteRepo !== githubRepo) {
    drifted.push(relative(SITE_MAIN_JS));
    if (!checkOnly) {
      writeText(SITE_MAIN_JS, patchSiteGithubRepo(siteContent, githubRepo));
    }
  }

  if (checkOnly) {
    if (drifted.length > 0) {
      console.error(
        `Version drift detected (source PROJECT_VERSION=${version}, DEFAULT_GITHUB_REPO=${githubRepo}). Run: npm run version:sync`,
      );
      for (const file of drifted) {
        console.error(`  - ${file}`);
      }
      process.exit(1);
    }
    console.log(`version:check ok (${version}, ${githubRepo})`);
    return;
  }

  if (drifted.length === 0) {
    console.log(`version:sync already up to date (${version}, ${githubRepo})`);
    return;
  }

  console.log(
    `version:sync wrote PROJECT_VERSION=${version}, DEFAULT_GITHUB_REPO=${githubRepo}`,
  );
  for (const file of drifted) {
    console.log(`  updated ${file}`);
  }
}

main();
